<script setup lang="ts">
/**
 * Icônes Material Design Icons, rendues en SVG inline depuis @mdi/js.
 * Le design system impose MDI et interdit les emoji. Seuls les glyphes nommés ici
 * entrent dans le bundle ; le nom suit la classe de la maquette (`mdi-compass-outline`
 * devient `compass-outline`).
 */
import {
  mdiLink,
  mdiDeleteOutline,
  mdiPlus,
  mdiSendOutline,
  mdiNotePlusOutline,
  mdiAccountMultiplePlusOutline,
  mdiFilterVariant,
  mdiChevronLeft,
  mdiCloseCircleOutline,
  mdiCloudOffOutline,
  mdiCodeJson,
  mdiFilePdfBox,
  mdiCashFast,
  mdiStorefrontOutline,
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArmFlexOutline,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowULeftTop,
  mdiBroadcast,
  mdiChartBoxOutline,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiChevronDown,
  mdiChevronRight,
  mdiCircleOutline,
  mdiCircleSlice4,
  mdiClockOutline,
  mdiClose,
  mdiCompassOutline,
  mdiContentCopy,
  mdiDownloadOutline,
  mdiEmailCheckOutline,
  mdiEmailOutline,
  mdiEyeOutline,
  mdiFileDocumentOutline,
  mdiFormatListNumbered,
  mdiHelpCircleOutline,
  mdiLinkVariant,
  mdiLinkedin,
  mdiLockOutline,
  mdiMenu,
  mdiRefresh,
  mdiShareVariantOutline,
  mdiShieldCheckOutline,
  mdiVectorIntersection,
  mdiWeatherCloudy,
  mdiWeatherLightningRainy,
  mdiWeatherPartlyCloudy,
  mdiWeatherRainy,
  mdiWeatherSunny,
  mdiWhatsapp,
  mdiLogout,
  mdiCogOutline,
  mdiPause,
  mdiDotsVertical,
  mdiMagnify,
  mdiHistory,
  mdiAccountPlusOutline,
  mdiEmailFastOutline,
  mdiEmailSyncOutline,
  mdiEyeOffOutline,
  mdiCalendarRange,
  mdiMinus,
  mdiAccountMultipleOutline,
  mdiClipboardListOutline,
  mdiViewDashboardOutline,
  mdiShieldAccountOutline,
  mdiSourceBranch,
  mdiOpenInNew,
  mdiKeyOutline,
  mdiCellphone,
  mdiCookieOutline,
  mdiGavel,
  mdiPencilOutline,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
} from '@mdi/js'

const ICONS: Record<string, string> = {
  'cloud-off-outline': mdiCloudOffOutline,
  'account-outline': mdiAccountOutline,
  'alert-circle-outline': mdiAlertCircleOutline,
  'alert-outline': mdiAlertOutline,
  'arm-flex-outline': mdiArmFlexOutline,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'arrow-u-left-top': mdiArrowULeftTop,
  broadcast: mdiBroadcast,
  'chart-box-outline': mdiChartBoxOutline,
  check: mdiCheck,
  'check-circle': mdiCheckCircle,
  'check-circle-outline': mdiCheckCircleOutline,
  'check-decagram': mdiCheckDecagram,
  'chevron-down': mdiChevronDown,
  'chevron-right': mdiChevronRight,
  'circle-outline': mdiCircleOutline,
  'circle-slice-4': mdiCircleSlice4,
  'clock-outline': mdiClockOutline,
  close: mdiClose,
  'compass-outline': mdiCompassOutline,
  'content-copy': mdiContentCopy,
  'download-outline': mdiDownloadOutline,
  'email-check-outline': mdiEmailCheckOutline,
  'email-outline': mdiEmailOutline,
  'eye-outline': mdiEyeOutline,
  'file-document-outline': mdiFileDocumentOutline,
  'format-list-numbered': mdiFormatListNumbered,
  'help-circle-outline': mdiHelpCircleOutline,
  'link-variant': mdiLinkVariant,
  linkedin: mdiLinkedin,
  'lock-outline': mdiLockOutline,
  menu: mdiMenu,
  refresh: mdiRefresh,
  'share-variant-outline': mdiShareVariantOutline,
  'shield-check-outline': mdiShieldCheckOutline,
  'vector-intersection': mdiVectorIntersection,
  'weather-cloudy': mdiWeatherCloudy,
  'weather-lightning-rainy': mdiWeatherLightningRainy,
  'weather-partly-cloudy': mdiWeatherPartlyCloudy,
  'weather-rainy': mdiWeatherRainy,
  'weather-sunny': mdiWeatherSunny,
  whatsapp: mdiWhatsapp,
  'cookie-outline': mdiCookieOutline,
  gavel: mdiGavel,
  'logout': mdiLogout,
  'cog-outline': mdiCogOutline,
  'pause': mdiPause,
  'dots-vertical': mdiDotsVertical,
  'magnify': mdiMagnify,
  'history': mdiHistory,
  'account-plus-outline': mdiAccountPlusOutline,
  'email-fast-outline': mdiEmailFastOutline,
  'email-sync-outline': mdiEmailSyncOutline,
  'eye-off-outline': mdiEyeOffOutline,
  'calendar-range': mdiCalendarRange,
  'minus': mdiMinus,
  'account-multiple-outline': mdiAccountMultipleOutline,
  'clipboard-list-outline': mdiClipboardListOutline,
  'view-dashboard-outline': mdiViewDashboardOutline,
  'shield-account-outline': mdiShieldAccountOutline,
  'source-branch': mdiSourceBranch,
  'open-in-new': mdiOpenInNew,
  'key-outline': mdiKeyOutline,
  'cellphone': mdiCellphone,
  'storefront-outline': mdiStorefrontOutline,
  'cash-fast': mdiCashFast,
  'file-pdf-box': mdiFilePdfBox,
  'code-json': mdiCodeJson,
  'close-circle-outline': mdiCloseCircleOutline,
  'chevron-left': mdiChevronLeft,
  'filter-variant': mdiFilterVariant,
  'account-multiple-plus-outline': mdiAccountMultiplePlusOutline,
  'note-plus-outline': mdiNotePlusOutline,
  'send-outline': mdiSendOutline,
  'plus': mdiPlus,
  'delete-outline': mdiDeleteOutline,
  'link': mdiLink,
  'pencil-outline': mdiPencilOutline,
  'chevron-double-left': mdiChevronDoubleLeft,
  'chevron-double-right': mdiChevronDoubleRight,
}

const props = withDefaults(defineProps<{ name: string; size?: number; label?: string }>(), {
  size: 24,
})
const path = computed(() => ICONS[props.name] ?? '')
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="currentColor"
    :role="label ? 'img' : undefined"
    :aria-hidden="label ? undefined : 'true'"
    :aria-label="label"
    class="inline-block shrink-0 align-middle"
  >
    <title v-if="label">{{ label }}</title>
    <path :d="path" />
  </svg>
</template>
